version: 2

before:
  hooks:
    - go mod tidy
    - go mod download
    - sh -c "cd web/admin && bun install --force"
    - sh -c "cd web/admin && bun run build"
    - sh -c "cd web/site && bun install --force"
    - sh -c "cd web/site && bunx @tailwindcss/cli -i ./src/input.css -o ./public/assets/css/style.css --minify"
    - ./scripts/webscripts

builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X "main.version=v{{.Version}}"
      - -X "main.gitCommit={{.ShortCommit}}"
      - -X "main.buildDate={{.Now.Format "2006-01-02"}}"
    main: ./cmd/main.go
    binary: litecart

archives:
  - name_template: '{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}'
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md

checksum:
  name_template: 'checksums.txt'

upx:
  - enabled: false

changelog:
  sort: asc
  filters:
    exclude:
      - init
      - '^.*?ci:'
      - '^.*?test:'
      - '^.*?build(deps):'
      - '^.*?build:'
      - 'README'
      - 'Up'
      - 'merge conflict'
      - Bump
      - Small fix
      - Update
      - Updating
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Security updates'
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 150
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 'Documentation updates'
      regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: 'Build process updates'
      regexp: ^.*?build(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999

dockers_v2:
  - id: dockerhub
    images:
      - 'shurco/litecart'
    tags:
      - 'v{{ .Version }}'
      - 'latest'
    platforms:
      - linux/amd64
      - linux/arm64
    dockerfile: Dockerfile.goreleaser
    flags:
      - '--pull'
    labels:
      'io.artifacthub.package.readme-url': 'https://raw.githubusercontent.com/shurco/litecart/main/README.md'
      'io.artifacthub.package.maintainers': '[{"name":"Dmitry Shurco"}]'
      'io.artifacthub.package.license': 'MIT'
      'org.opencontainers.image.description': '🛒 litecart - shopping-cart in 1 file'
      'org.opencontainers.image.created': '{{.Date}}'
      'org.opencontainers.image.name': '{{.ProjectName}}'
      'org.opencontainers.image.revision': '{{.FullCommit}}'
      'org.opencontainers.image.version': '{{.Version}}'
      'org.opencontainers.image.source': '{{.GitURL}}'

  - id: ghcr
    images:
      - 'ghcr.io/shurco/litecart'
    tags:
      - 'v{{ .Version }}'
      - 'latest'
    platforms:
      - linux/amd64
      - linux/arm64
    dockerfile: Dockerfile.goreleaser
    flags:
      - '--pull'
    labels:
      'io.artifacthub.package.readme-url': 'https://raw.githubusercontent.com/shurco/litecart/main/README.md'
      'io.artifacthub.package.maintainers': '[{"name":"Dmitry Shurco"}]'
      'io.artifacthub.package.license': 'MIT'
      'org.opencontainers.image.description': '🛒 litecart - shopping-cart in 1 file'
      'org.opencontainers.image.created': '{{.Date}}'
      'org.opencontainers.image.name': '{{.ProjectName}}'
      'org.opencontainers.image.revision': '{{.FullCommit}}'
      'org.opencontainers.image.version': '{{.Version}}'
      'org.opencontainers.image.source': '{{.GitURL}}'

release:
  name_template: "v{{ .Version }}"
  header: |
    > *To update the prebuilt executable you can run `./litecart update`*

  footer: |
    **Full Changelog**: https://github.com/shurco/litecart/compare/{{ .PreviousTag }}...{{ .Tag }}
    
    > [!WARNING]
    > If you are updating, it is essential to do the following - back up the **./site** folder if you have made changes to it (you can rename it). A new folder with updated files will be created.

announce:
  mastodon:
    enabled: true
    message_template: "#litecart {{ .Tag }} is out! Check it out: https://github.com/shurco/litecart/releases/tag/{{ .Tag }}"
    server: https://mastodon.social
