@host = http://localhost:8080

###
# @name install
POST {{host}}/api/install
Content-Type: application/json

{
    "email":"user@mail.com",
    "password":"Pass123"
}


###
# @name install2
POST {{host}}/api/install
Content-Type: application/json

{
    "email":"user@mail.com",
    "password":"Pass123",
    "domain":"site.com",
    "stripe_secret":"sk_test_000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000" 
}