@host = http://localhost:8080

###
# @name signin
POST {{host}}/api/sign/in
Content-Type: application/json

{
    "email":"user@mail.com",
    "password":"Pass123"
}

###
# @name products
GET {{host}}/api/_/products

###
# @name fake_product
GET {{host}}/api/_products/123456789012345

###
# @name product
GET {{host}}/api/_/products/fv6c9s9cqzf36sc

###
# @name active
PATCH {{host}}/api/_/products/active/fv6c9s9cqzf36sc


###
# @name image_add
POST {{host}}/api/_/products/fv6c9s9cqzf36sc/image

###
# @name image_delete
DELETE {{host}}/api/_/products/fv6c9s9cqzf36sc/image/dj9bae53oob0ukj

###
# @name product_digital
GET {{host}}/api/_/products/xrtb1b919t2nuj9/digital

###
# @name product_digital_fake
GET {{host}}/api/_/products/fv6c9s9cqzf36s2/digital

