#!/usr/bin/env bash

#set -e

ROOT_PATH="$(git rev-parse --show-toplevel)"
source ${ROOT_PATH}/scripts/_helper

WEB=$1

if [[ $WEB == "admin" ]]; then
  cd $ROOT_PATH/web/admin && tailwindcss -o ./public/assets/css/style.css --watch --minify
elif [[ $MIGRATION == "site" ]]; then
  cd $ROOT_PATH/web/site && tailwindcss -o ./public/assets/css/style.css --watch --minify
else
  print_header "Tailwind CLI"
  print_answer "ERROR" red
  echo "Parameters not passed"
  echo
  echo "Use next command:"
  print_help admin "Run Tailwind CLI for admin folder"
  print_help site "Run Tailwind CLI for site folder"
  exit
fi
