#!/usr/bin/env bash

#set -e

ROOT_PATH="$(git rev-parse --show-toplevel)"
source ${ROOT_PATH}/scripts/_helper

print_header "Install/Update vue"
VUECORE_LATEST=$(get_latest_release "vuejs/core")
wget "https://unpkg.com/vue@${VUECORE_LATEST:1}/dist/vue.global.prod.js" -4 -q -O ${ROOT_PATH}/web/site/public/assets/js/vue.js
print_answer "SUCCESS" green
